parameters:
#    wdr_stroibat.example.class: Wdr\StroibatBundle\Example

services:
#    wdr_stroibat.example:
#        class: %wdr_stroibat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
